[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/rally-detail/*"
  to = "/rally-detail/[id]"
  status = 200

[[headers]]
  for = "/rally-detail/*"
  [headers.values]
    X-Custom-Header = "Rally Detail Page"
