[build]
  command = "npm run build"
  publish = ".next"

[[redirects]]
  from = "/rally-detail/*"
  to = "/rally-detail/[id]"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
