name: Backup Repository

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Backup
        run: |
          mkdir -p backups
          tar -czvf backups/rally-planner-backup-$(date +"%Y%m%d").tar.gz .
      
      - name: Upload Backup
        uses: actions/upload-artifact@v3
        with:
          name: rally-planner-backup
          path: backups
